version: '2'
services:
  mysql:
    image: mysql:5.7
    ports:
      - 3306:3306

    environment:
      - LANG=C.UTF-8
      - TERM=dumb
      - MYSQL_ROOT_PASSWORD=mahong
      - MYSQL_DATABASE=mahong
      - MYSQL_PASSWORD=mahong
      - MYSQL_USER=mahong
    networks:
      main:
        aliases:
          - mysql


  Spring:
    image: java:8-jdk-alpine
    ports:
      - 8080:8080
    volumes:
          - ./target/demo-0.0.1-SNAPSHOT.jar:/usr/src/myapp/spring-boot-demo-0.0.1.jar
    command: java -jar /usr/src/myapp/spring-boot-demo-0.0.1.jar
    networks:
      main:
        aliases:
          - spring

networks:
  main: