server:
  context-path: /springboot
  port: 8888

name: 小胖
age: 22
content: "name: ${name},age: ${age}"

person:
  name: 小胖
  age: 22

spring:
  profiles:
    active: dev
  datasource:
      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://localhost:3306/mahong
      username: mahong
      password: mahong

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect : org.hibernate.dialect.MySQL5Dialect
    show-sql: true


---

# 开发环境配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://192.168.100.107:3306/mahong


---
# 测试环境配置
spring:
  profiles: test
  datasource:
    url: jdbc:mysql://10.205.22.117:3306/test
